openapi: 3.0.3
info:
  title: Warehouse Management System
  description: REST API for managing warehouses, inventory, products, picking, and orders
  version: 1.0.0
  contact:
    name: Warehouse Management System
    email: spanitechrayslabs@gmail.com

servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/techrayslabs-5b1/w.m.s/1.0.0
  - url: http://localhost:8080/api

paths:
  
  /warehouses/{warehouse_id}:
    get:
      tags: [Warehouse]
      summary: Get warehouse by ID
      parameters:
        - name: warehouse_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Warehouse details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Warehouse"

    put:
      tags: [Warehouse]
      summary: Update warehouse
      parameters:
        - name: warehouse_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Warehouse"
      responses:
        "200":
          description: Warehouse updated

  /roles:
    get:
      tags: [Role]
      summary: Get all roles
      responses:
        "200":
          description: Roles list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Role"

    post:
      tags: [Role]
      summary: Create role
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Role"
      responses:
        "201":
          description: Role created

  /purchase_order:
    get:
      tags: [purchase_order]
      summary: Get all warehouses
      responses:
        "200":
          description: List of warehouses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/purchase_order"
    post:
      tags: [purchase_order]
      summary: Create role
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/purchase_order'
      responses:
        "201":
          description: order purchased     
    patch:
      tags: [purchase_order]
      summary: Get all warehouses
      responses:
        "200":
          description: List of warehouses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/purchase_order" 
    delete:
      tags: [purchase_order]
      summary: Get all warehouses
      responses:
        "200":
          description: List of warehouses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/purchase_order"                            
            

  /zones:
    get:
      tags: [Zone]
      summary: Get zones
      responses:
        "200":
          description: Zones list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Zone"

    post:
      tags: [Zone]
      summary: Create zone
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Zone"
      responses:
        "201":
          description: Zone created

  /inventory:
    get:
      tags: [Inventory]
      summary: Get inventory
      responses:
        "200":
          description: Inventory list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Inventory"

    post:
      tags: [Inventory]
      summary: Add inventory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Inventory"
      responses:
        "201":
          description: Inventory added

    put:
      tags: [Inventory]
      summary: Get all warehouses
      responses:
        "200":
          description: List of warehouses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/purchase_order"  
    delete:
      tags: [Inventory]
      summary: Get all warehouses
      responses:
        "200":
          description: List of warehouses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/purchase_order"                  

  /inventory/{inventory_id}:
    patch:
      tags: [Inventory]
      summary: Update inventory quantity
      parameters:
        - name: inventory_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Inventory"
      responses:
        "200":
          description: Inventory updated

  /products:
    get:
      tags: [Product]
      summary: Get products
      responses:
        "200":
          description: Product list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"

    post:
      tags: [Product]
      summary: Add product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "201":
          description: Product created

  /products/{product_id}:
    patch:
      tags: [Product]
      summary: Update product
      parameters:
        - name: product_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "200":
          description: Product updated

  /picking:
    get:
      tags: [Picking]
      summary: Get picking records
      responses:
        "200":
          description: Picking list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Picking"

    post:
      tags: [Picking]
      summary: Create picking task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Picking"
      responses:
        "201":
          description: Picking created

  

components:
  schemas:

    Warehouse:
      type: object
      properties:
        warehouse_id:
          type: integer
        managed_by:
          type: string
        country:
          type: string
        role_id:
          type: integer

    Role:
      type: object
      properties:
        role_id:
          type: integer
        role_name:
          type: string

    Zone:
      type: object
      properties:
        zone_id:
          type: integer
        warehouse_id:
          type: integer
        zone_type:
          type: string

    Inventory:
      type: object
      properties:
        inventory_id:
          type: integer
        zone_id:
          type: integer
        product_id:
          type: integer
        quantity:
          type: integer

    Product:
      type: object
      properties:
        product_id:
          type: integer
        product_name:
          type: string
        category:
          type: string
        unit:
          type: string

    Picking:
      type: object
      properties:
        picking_id:
          type: integer
        status:
          type: string
        sales_id:
          type: string

    purchase_order:
      type: object
      properties:
        purchase_order_id:
          type: integer
        supplier_id: 
          type: integer
        status: 
          type: string